import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Blue Evolution",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Aquí defines el tema que quieres usar por defecto o mediante prop/contexto
  const variant: "light" | "dark" = "light";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="font-sans transition-all duration-500 min-h-screen flex flex-col">
          {/* Navbar fijo arriba */}
          <header>
            <Navbar variant={variant} />
          </header>
          {/* Contenido principal: que crece y ocupa espacio */}
            {children}
          {/* Footer abajo */}
          <footer>
            <Footer variant={variant} />
          </footer>
        </div>
      </body>
    </html>
  );
}
